######################################################################
# Automatically generated by qmake (3.0) jeu. juil. 3 11:46:56 2014
######################################################################

TEMPLATE = app
TARGET = tester
INCLUDEPATH += .
QT += widgets
QT += network

# Input
HEADERS += MainUI.hpp
SOURCES += main.cpp MainUI.cpp
