######################################################################
# Automatically generated by qmake (3.0) mer. juin 18 16:27:26 2014
######################################################################

TEMPLATE = app
TARGET = gui
INCLUDEPATH += . header
QT += widgets
CONFIG += c++11

# Input
HEADERS += header/MainUI.hpp header/MainGUI.hpp header/Network.hpp
SOURCES += srcs/main.cpp srcs/MainUI.cpp srcs/MainGUI.cpp srcs/Network.cpp
